#151168132 Users should see a landing page with effective UI/UX
andela/rainier-cfh pull request #14
Opened 2017-09-25 19:11 UTC by gbengaPS

#### What does this PR do?
Complete redesign of the landing page.

#### Description of Task to be completed?
Users should be able to see an overview of what the game is about, how it's played and how it can be used to donate to charity and also see call to action buttons that lead them to signup or signin

#### How should this be manually tested?
Can be tested  by running npm test

#### What are the relevant pivotal tracker stories?
Users should see a landing page with effective UI/UX

#### Screenshots (if appropriate)

![localhost-3000-](https://user-images.githubusercontent.com/8515311/30825593-6cb1e90a-a22b-11e7-9d2e-67939a754afe.png)

2017-09-26 09:52 UTC, andela-iadeniyi commented on app/views/includes/head.jade
> +  //- link(rel='stylesheet', href='/lib/bootstrap/css/bootstrap.css')
Remove unused code

2017-09-26 09:59 UTC, ibonly requested changes
PR require update

2017-09-26 23:10 UTC, ibonly approved these changes

2017-09-27 12:08 UTC, nebanat approved these changes

2017-09-27 14:32 UTC, merged