#151168135 Re-Design UI for user authentication screen
andela/rainier-cfh pull request #15
Opened 2017-09-26 18:28 UTC by enodi

**What does this PR do?**
Redesign of user signup and signin page

**Description of Task to be completed?**
Users should be able to see a redesigned signup/signin page with option to authenticate via twitter, github, facebook and google

**What are the relevant pivotal tracker stories?**
#151168135 - Re-Design UI for user authentication screen

**Screenshots (if appropriate)**
![image](https://user-images.githubusercontent.com/29783644/30877182-d9454d62-a2f0-11e7-8ea6-eb25e07b7a8a.png)

2017-09-26 23:07 UTC, ibonly requested changes
More than 5 files changed and just 2 commit messages, how come?

2017-09-27 11:22 UTC, gbengaoyetade requested changes

2017-09-27 11:22 UTC, gbengaPS commented on app/views/includes/head.jade
> +  //- link(rel='stylesheet', href='/css/animate.css')
Remove unused code

2017-09-27 11:22 UTC, gbengaPS commented on server.js
> +// const db = mongoose.connect('mongodb://localhost/rainier-cfh');
Remove redundant code

2017-09-27 11:22 UTC, gbengaPS commented on app/controllers/users.js
> +// const dotenv = require('dotenv');
remove redundant code

2017-09-27 11:49 UTC, dinobi approved these changes
Seen

2017-09-27 14:25 UTC, gbengaoyetade approved these changes

2017-09-27 14:30 UTC, ibonly approved these changes

2017-09-27 14:47 UTC, merged