#151168131 send invites other users
andela/rainier-cfh pull request #16
Opened 2017-09-26 21:36 UTC by nebanat

#### What does this PR do?
Users are able to search for other users and send them game invite via Email.
#### Description of Task to be completed?
- When a user starts a game and wants to invite other friends to join the game
- User can click on the 'invite other users' button to see a modal with a search box
- User can then search and send invites to other users
- Invited users can see link to join the game in their emails
#### How should this be manually tested?
- On the main gaming page users should be able search and send invites to friends
#### Any background context you want to provide?
Used nodemailer to send emails. Nodemailer is an effective node package for sending in-app notifications in node application 
#### What are the relevant pivotal tracker stories?
Story type: Feature
Story Id: 151168131
Story: Users should be able to send invites to at most 11 people other than themselves
#### Screenshots 
![screenshot1](https://user-images.githubusercontent.com/24405172/30885156-27a0914c-a30a-11e7-9978-8893dee51f02.jpeg)
![screenshots 2](https://user-images.githubusercontent.com/24405172/30885396-001acb6e-a30b-11e7-9df0-fbfeaca74fdf.jpeg)
![screenshots 3](https://user-images.githubusercontent.com/24405172/30885410-0f7a4f30-a30b-11e7-945f-0a5152f02298.jpeg)

#### Questions:

2017-09-26 22:56 UTC, andela-iadeniyi commented on app/controllers/users.js
> +      user: 'abiliyok@gmail.com',
This is not a good practice, pass this through your environment variable.

2017-09-26 23:02 UTC, andela-iadeniyi commented on .env
> +MONGOHQ_URL=mongodb://localhost:27017/cfh
This file should be deleted, .env file is specific to the application configuration on your local machine!!!

2017-09-26 23:04 UTC, ibonly requested changes
Get 2 more reviewers when you fix the review.

2017-09-27 14:26 UTC, enodi approved these changes

2017-09-27 14:45 UTC, dinobi approved these changes
Seen

2017-09-27 15:53 UTC, ibonly approved these changes

2017-09-27 17:21 UTC, merged