#151476592 fix landing page links
andela/rainier-cfh pull request #18
Opened 2017-09-27 18:37 UTC by gbengaPS

#### What does this PR do?
Makes each link on the landing page conform to its reference

#### Description of Task to be completed?
Users should be able to link from the landing page to other links provided on the landing page.

#### How should this be manually tested?
Visit the landing page of the app and click each link

#### Any background context you want to provide?
n/a
#### What are the relevant pivotal tracker stories?
Connect each link on the landing page to it's destination

2017-09-27 20:00 UTC, enodi requested changes

2017-09-27 20:00 UTC, enodi commented on app/views/includes/head.jade
> +  //- link(rel="stylesheet" href="../css/style.css")
remove unused code

2017-09-27 20:00 UTC, enodi commented on public/css/style.css
> +} */
remove unused code

2017-09-27 20:00 UTC, enodi commented on public/views/index.html
> +      <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> -->
remove unused code

2017-09-28 08:13 UTC, segunolalive requested changes

2017-09-28 08:13 UTC, segunolalive commented on app/views/includes/head.jade
> +  //- link(rel="stylesheet" href="../css/style.css")
remove this line.

style.css is included in another line

2017-09-28 12:14 UTC, enodi approved these changes

2017-09-28 12:48 UTC, segunolalive approved these changes

2017-09-28 12:58 UTC, ibonly approved these changes

2017-09-28 13:09 UTC, merged