Feature/151168137/gaming screen
andela/rainier-cfh pull request #25
Opened 2017-10-03 15:26 UTC by segunolalive

#### What does this PR do?
Redesigns the gaming screen

#### Description of Task to be completed?
Re-Design UI for the actual gaming screen

#### How should this be manually tested?
npm start

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
#151168137

#### Screenshots (if appropriate)
![localhost-3000- 1](https://user-images.githubusercontent.com/16195512/31133480-8bef8192-a857-11e7-829c-15b4c38a1c95.png)
![localhost-3000- iphone 6 plus](https://user-images.githubusercontent.com/16195512/31133481-8bf005a4-a857-11e7-94fb-46900db3d876.png)

2017-10-04 12:35 UTC, nebanat requested changes
Please make the appropriate change

2017-10-04 12:35 UTC, nebanat commented on app/controllers/answers.js
> +      message: 'Question added successfully',
Please change message to 'Answer added successfully'.

2017-10-04 13:36 UTC, dinobi commented on config/routes.js
> -  app.post('/api/answers/add', answers.add);
This route was removed, any reason for that?

2017-10-04 13:36 UTC, dinobi commented on config/routes.js
> -  app.post('/api/questions/add', questions.add);
This route was removed, any reason for that

2017-10-04 18:18 UTC, nebanat approved these changes

2017-10-04 18:20 UTC, merged

2017-10-05 08:31 UTC, andela-iadeniyi commented
Why was this PR merged without my approval?

2017-10-05 10:36 UTC, segunolalive commented
I'm sorry. This merge was a mistake. It shouldn't have been merged yet